apiVersion: v1
kind: ConfigMap
metadata:
  name: basset0-config
  labels:
    app.kubernetes.io/name: basset0
data:
  INSTANCE_DOMAIN: 'api.topia.io'
  INSTANCE_PROTOCOL: 'https'
  INTERACTIVE_KEY: 'qz37yqVSpMLyeYtz2o1a'
  PORT: '3000'
  IMG_ASSET_ID: 'webImageAsset'
  NODE_ENV: 'production'
  BASE_URL: 'https://basset0-dev-topia.topia-rtsdk.com'
  S3_BUCKET: 'sdk-build-an-asset'
  S3_BUCKET_BUILD_AN_ASSET: 'sdk-build-an-asset'
