name: AWS-Deploy

on:
  push:
    branches: [dev]
  workflow_dispatch:
env:
  REGISTRY: '368076259134.dkr.ecr.us-east-1.amazonaws.com'
  REPOSITORY: 'sdk-example'
  IMAGE_TAG: ${{ github.event.repository.name }}

concurrency:
  group: ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
        
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        
      - uses: actions/setup-node@v4.0.1
        with:
          node-version: 20.10
          cache: 'npm'
      - run: npm i
      - run: CI=false npm run build:prod
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: arn:aws:iam::368076259134:role/github-actions-role
          aws-region: us-east-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1.7.1

      - name: Build
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG  .

      - name: push docker image to Amazon ECR
        run: |
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
          
      - name: Publish
        run: |
          aws ecs update-service --service sdk-snowman-dev-topia0-svc --force-new-deployment --cluster SDK-Example-CLS
